#!/usr/bin/perl

use POSIX;
use XML::Parser;

#http://www.overpass-api.de/api/xapi?map?bbox=-122.51781,37.716045,-122.34924,37.817006
#SF
#$minlat = 37.716045;
#$minlon = -122.51781;
#$maxlat = 37.817006;
#$maxlon = -122.34924;

$minlat = $ARGV[1];
$minlon = $ARGV[2];
$maxlat = $ARGV[3];
$maxlon = $ARGV[4];

$head = "{\"type\": \"FeatureCollection\", \"features\": [ ";
$body = "";
$foot = "]}";
sub handle_start {

	my ($expat, $element, @tags) = @_;
	my %tags = @tags;

	if ($element eq "node") {
		$lat = $tags{'lat'};
		$lon = $tags{'lon'};

		if ($lat >= $minlat && $lat <= $maxlat && $lon >= $minlon && $lon <= $maxlon) {
			$lat{$tags{'id'}} = $lat;
			$lon{$tags{'id'}} = $lon;
		}
	}

	if ($element eq "way") {
		$timestamp = $tags{'timestamp'};
		$user = $tags{'user'};
		@nd = ();
	}

	if ($element eq "nd") {
		push @nd, $tags{'ref'};
	}
}

sub handle_end {
	my ($expat, $element,) = @_;

	if ($element eq "way") {
		@lat = ();
		@lon = ();

		for $n (@nd) {
			if (defined($lat{$n})) {
				push @lat, $lat{$n};
				push @lon, $lon{$n};
			} else {
				push @lat, 0;
				push @lon, 0;
			}
		}
		

		for ($i = 0; $i < $#lat; $i++) {


			if ($lat[$i] != 0 && $lat[$i + 1] != 0) {
				if($user eq "j03lar50n" || $user eq "chadbunn" || $user eq "e*holtz"|| $user eq "Kat Konstantinidis" || $user eq "Station 42" || $user eq "michaelaL" || $user eq "jotaylor" || $user eq "Chief Tri-tip" || $user eq "Marshy8" || $user eq "MannequinBaby || $user eq "JuliaEstrada" || $user eq "briandelro" || $user eq "Station 10" || $user eq "slocoff" || $user eq "JonCPSU" || $user eq "Shanniga10" || $user eq "slo_osm_imports" || $user eq "devinpp" || $user eq "tdavisson_td" || $user eq "tabiko" || $user eq "MLuna" || $user eq "hpanno" || $user eq "CoreyFarwell" || $user eq "Karen Sullivan" || $user eq "DJuarez" || $user eq "cbergin" || $user eq "Brad DeBranch" || $user eq "RoccoMap21" || $user eq "danziebron" || $user eq "Ryangee727" || $user eq "DrChapman" || $user eq "njliu" || $user eq "edgrmdna" || $user eq "Dani_770" || $user eq "joeypersico" || $user eq "H20CalFire" || $user eq "nl519"){
					print "   {
			      \"type\": \"Feature\",
			      \"properties\": {\"user\":\"$user\"},
			      \"geometry\": {
			        \"type\": \"LineString\",
			        \"coordinates\": [
			          [$lon[$i] , $lat[$i] ],
			          [$lon[$i + 1], $lat[$i + 1]]
			        ]
			      }
			    },";
				}
				
			}
		}
		
	}
}

	$n1=$ARGV[0];
	print STDERR "$ARGV[0]\n";
	$parser = new XML::Parser(Handlers => { Start => \&handle_start, End => \&handle_end, });
	print $head;
	open(IN, "zcat $n1 |");
	$parser->parse(*IN);
	print "{
			    \"type\": \"Feature\",
			    \"properties\": {},
			    \"geometry\": {
			    \"type\": \"LineString\",
			      \"coordinates\": []			       
			    }
			}";
	print $foot;
	close(IN);

